#!/bin/bash

DIR="$HOME/dwm/rofi/"

rofi \
	-show drun \
	-modi run,drun,ssh \
	-no-lazy-grab \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-no-drun-show-actions \
	-terminal st \
	-theme "$DIR"/simple-tokyonight.rasi
